name: itslive-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3
  - fiona
  - ipyleaflet
  - ipympl
  - matplotlib-base
  - pandas
  - psutil
  - pyproj
  - ipyflex
  - s3fs>=2021.11
  - shapely
  - sidecar
  - xarray
  - zarr
